from django.urls import path, re_path

from . import views

urlpatterns = [
    path('recipes/basket/',
         views.BasketView.as_view(),
         name='recipe_basket'),
    path('recipes/basket/download',
         views.BasketDownloadView.as_view(),
         name='recipe_basket_download'),
    path('recipes/create_recipe/',
         views.RecipeCreateView.as_view(),
         name='create_recipe'),
    path('recipes/<int:pk>/',
         views.RecipeDetailView.as_view(),
         name='recipe'),
    path('recipes/<int:pk>/edit/',
         views.RecipeEditView.as_view(),
         name='recipe_edit',),
    path('recipes/<int:pk>/delete/',
         views.RecipeDeleteView.as_view(),
         name='recipe_delete',),
    path('recipes/follow/',
         views.FollowView.as_view(),
         name='recipe_follow'),
    path('ingredients/',
         views.GetIngredient.as_view(),
         name='ingredients'),
    path('subscriptions/',
         views.SubscriptionView.as_view(),
         name='subscription'),
    path('favorites/',
         views.FavoriteView.as_view(),
         name='favorites'),
    path('recipes/favorite/',
         views.FavoriteListView.as_view(),
         name='recipe_favorite'),
    path('profile/<int:pk>/',
         views.ProfileView.as_view(),
         name='profile'),
    re_path(r'^purchases/(?:(?P<id>\d+)/)?$',
         views.PurchaseView.as_view(),
         name='purchases'),
    path('',
         views.RecipeListView.as_view(),
         name='index'),
]
